export const APPLICATION_LOADING_START = "APPLICATION_LOADING_START";
export const APPLICATION_LOADING_END = "APPLICATION_LOADING_END";
export const SET_BOTTOM_NAV_ACTIVE = "SET_BOTTOM_NAV_ACTIVE";

export const POKEMON_LIST_SUCCESS = "POKEMON_LIST_SUCCESS";
export const POKEMON_GET_SUCCESS = "POKEMON_GET_SUCCESS";
export const POKEMON_ACTION_SUCCESS = "POKEMON_ACTION_SUCCESS";
export const POKEMON_SET_MY_LIST = "POKEMON_SET_MY_LIST";
export const POKEMON_ERROR = "POKEMON_ERROR";
export const POKEMON_CLEAR_DATA = "POKEMON_CLEAR_DATA";
export const POKEMON_CLEAR_STATE = "POKEMON_CLEAR_STATE";
